apiVersion: v1
kind: Service
metadata:
  name: fleetmap-webapp
spec:
  # this defines which pods are going to be represented by this service
  # The service becomes a network endpoint for other services
  # or external users (e.g. browser)
  selector:
    app: webapp

  ports:
    - name: http
      port: 80
      nodePort: 30080

  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: queue

  ports:
    - name: http
      port: 8161
      nodePort: 30010 # to expose it to outside the cluster

    - name: endpoint
      port: 61616

  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  selector:
    app: position-tracker

  ports:
    - name: http
      port: 8080

  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  selector:
    app: api-gateway

  ports:
    - name: http
      port: 8080

  type: ClusterIP